### ISSUE TITLE
Loosen @storybook/addons dependency

### ISSUE THREAD

**Issue by Undistraction** [rubenillodo/storybook-styled-components-theme-selector#7]
Please can you loosen the dependency on `@storybook/addons` so that using Storybook v6 (and `storybook/addons@6.x.x`) doesn't trigger a peer dependency warning.

For example with `@storybook/addons": "^6.0.26"`:

> warning "workspace-aggregator-d416b74f-8aa9-4ab3-86c3-a9481a1e54d8 > storybook-styled-components-theme-selector@1.0.0" has incorrect peer dependency "@storybook/addons@^5.3.0".

**Comment by rubenillodo** [comment]
Thank you very much for the suggestion.

`v1.1.0` should improve this.
